[build]
  publish = "."

[[redirects]]
  from = "/leaderboard"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/leaderboard/"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/play"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/play/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://diy-air-purifier-leaderboard.essays-loges0y.workers.dev/api/:splat"
  status = 200
  force = true
