[build]
  command = "npm run vite:build"
  publish = "dist"

[[redirects]]
  from = "/"
  to = "/vite-index.html"
  status = 200

[[redirects]]
  from = "/index.html"
  to = "/vite-index.html"
  status = 301

[[redirects]]
  from = "/leaderboard"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/leaderboard/"
  to = "/leaderboard.html"
  status = 200

[[redirects]]
  from = "/play"
  to = "/vite-index.html"
  status = 200

[[redirects]]
  from = "/play/"
  to = "/vite-index.html"
  status = 200

[[redirects]]
  from = "/old"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/old/"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/admin/"
  to = "/admin.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "https://diy-air-purifier-leaderboard.essays-loges0y.workers.dev/api/:splat"
  status = 200
  force = true
